# Uncomment and fill in any line below to surface a sponsor button on the repo.
# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# github: sachincool
# ko_fi: your-handle
# buy_me_a_coffee: your-handle
# custom: ["https://example.com/sponsor"]
