package iac

import (
	"context"
	"fmt"
	"time"

	"github.com/sachincool/cruft/internal/cleaner"
	"github.com/sachincool/cruft/internal/fsutil"
	"github.com/sachincool/cruft/internal/tombstone"
)

type tfCleaner struct{}

func init() { cleaner.Register(&tfCleaner{}) }

func (tfCleaner) Name() string               { return "terraform" }
func (tfCleaner) Category() cleaner.Category { return cleaner.CategoryIaC }
func (tfCleaner) Description() string {
	return "Stale .terraform/ provider caches under projects you haven't touched in --stale-days. Real state is in your remote backend; only the local plugin cache is removed."
}
func (tfCleaner) Risky() bool             { return false }
func (tfCleaner) RiskReason() string      { return "" }
func (tfCleaner) BusyProcesses() []string { return []string{"terraform"} }

func (tfCleaner) Detect(ctx context.Context) bool {
	// We don't require the terraform binary — we're only cleaning
	// directories left behind by it.
	return true
}

func (tfCleaner) Scan(ctx context.Context, opts cleaner.ScanOpts) ([]cleaner.Finding, error) {
	roots := opts.SearchRoots
	if len(roots) == 0 {
		roots = defaultSearchRoots()
	}
	stale, err := fsutil.FindStaleDirs(ctx, roots, ".terraform", []string{".tf"}, opts.StaleDays)
	if err != nil {
		return nil, err
	}
	out := make([]cleaner.Finding, 0, len(stale))
	for _, d := range stale {
		s, err := fsutil.Size(ctx, d.Path, opts.SamplePaths)
		if err != nil || s.Bytes == 0 {
			continue
		}
		samples := make([]cleaner.SamplePath, 0, len(s.SamplePaths))
		for _, sp := range s.SamplePaths {
			samples = append(samples, cleaner.SamplePath{Path: sp.Path, Bytes: sp.Bytes, LastModified: sp.LastModified})
		}
		out = append(out, cleaner.Finding{
			Path:         d.Path,
			Bytes:        s.Bytes,
			LastModified: d.NewestProjectMod,
			Reason:       fmt.Sprintf("project untouched %dd in %s", d.AgeDays, d.ProjectDir),
			SamplePaths:  samples,
		})
	}
	return out, nil
}

func (tfCleaner) Execute(ctx context.Context, findings []cleaner.Finding, opts cleaner.ExecOpts) (cleaner.Result, error) {
	return executeStale(ctx, "terraform", ".terraform", findings, opts)
}

func defaultSearchRoots() []string {
	return []string{"~/Projects", "~/projects", "~/code", "~/work", "~/src", "~/dev"}
}

// executeStale is shared by the terraform / terragrunt cleaners.
// Findings were generated by FindStaleDirs scanning for wantBase dirs;
// re-check the basename at execute time so a finding can never be
// redirected at anything but a directory of that exact name. The
// symlink case is handled inside SafeRemove (the final path element is
// never followed).
func executeStale(ctx context.Context, name, wantBase string, findings []cleaner.Finding, opts cleaner.ExecOpts) (cleaner.Result, error) {
	res := cleaner.Result{Cleaner: name, Findings: len(findings), DryRun: opts.DryRun}
	for _, f := range findings {
		if err := ctx.Err(); err != nil {
			break
		}
		entry := cleaner.AuditEntry{
			Timestamp:  time.Now(),
			RunID:      opts.RunID,
			Cleaner:    name,
			Path:       f.Path,
			Bytes:      f.Bytes,
			DryRun:     opts.DryRun,
			Tombstoned: opts.UseTombstone,
		}
		if opts.DryRun {
			entry.Success = true
			opts.AuditLog.Record(entry)
			res.Succeeded++
			res.BytesFreed += f.Bytes
			continue
		}
		if pathBase(f.Path) != wantBase {
			err := fmt.Errorf("refused: %s is not a %s directory", f.Path, wantBase)
			res.Failed++
			res.Errors = append(res.Errors, err)
			entry.Error = err.Error()
			opts.AuditLog.Record(entry)
			continue
		}
		if opts.UseTombstone && opts.Tombstone != "" {
			store := tombstone.New(pathDir(opts.Tombstone))
			if _, err := store.Bury(pathBase(opts.Tombstone), name, f.Path); err != nil {
				res.Failed++
				res.Errors = append(res.Errors, err)
				entry.Error = err.Error()
				opts.AuditLog.Record(entry)
				continue
			}
		} else {
			// Whitelist scoped to exactly this finding's path.
			if err := fsutil.SafeRemove(f.Path, []string{f.Path}); err != nil {
				res.Failed++
				res.Errors = append(res.Errors, err)
				entry.Error = err.Error()
				opts.AuditLog.Record(entry)
				continue
			}
		}
		entry.Success = true
		opts.AuditLog.Record(entry)
		res.Succeeded++
		res.BytesFreed += f.Bytes
	}
	return res, nil
}
